- name: Node exporter build
  hosts: vps
  become: yes
  tasks:
    - name: Check connectivity
      ping:

    - name: Define Node Exporter version
      set_fact:
        node_exporter_version: "1.7.0"

    - name: Download Node Exporter binary
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        validate_certs: yes

    - name: Decompression
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Add user node_exporter
      user:
        name: node_exporter
        shell: /bin/false
        create_home: false

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/opt/node_exporter/node_exporter

          [Install]
          WantedBy=multi-user.target
    - name: Start and enable service
      systemd:
        daemon_reload: yes
        name: node_exporter
        enabled: yes
        state: started
    # - name: Update firewall rules
    #   ufw:
    #     rule: allow
    #     port: 9100
    #     proto: tcp
