scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:9200

- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - node_exporter:9100
